# Generated by Django 4.1.6 on 2023-02-08 18:50

from django.db import migrations, models
import modeltranslation_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltranslation_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.JSONField(default=modeltranslation_app.models.default_language_dict, verbose_name='Blog title')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.JSONField(default=modeltranslation_app.models.default_language_dict, verbose_name='Article title'),
        ),
    ]
