# Generated by Django 4.1.6 on 2023-02-13 01:16

from django.db import migrations, models
import modeltranslation_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltranslation_app', '0002_blog_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.JSONField(default=modeltranslation_app.models.default_language_dict, verbose_name='Article Dexcription'),
        ),
    ]
